### ISSUE TITLE
there is a problem with google login

### ISSUE THREAD

**Issue by mynameismhmd** [mustafaaycll/shoeshop#1]
I don't know what it is maybe you didn't add sha1

**Comment by mustafaaycll** [comment]
If I am not mistaken, android emulator needs play store services installed in the emulator for google login to work. Did you launch a play store-enabled-emulator? As far as I remember, it simply does not work on iOS emulator.

**Comment by mynameismhmd** [comment]
yea just check the login my app works with google login but yours no did you add sha 1 to it

**Comment by mynameismhmd** [comment]
I can test it with mine but the products don't show if I'm using my google.json that's why I need yours

**Comment by mustafaaycll** [comment]
Google login is no longer a feature

**Comment by mynameismhmd** [comment]
haha of course it is nice joke
