### ISSUE TITLE
no products shown when using different google.json

### ISSUE THREAD

**Issue by mynameismhmd** [mustafaaycll/shoeshop#2]
I don't know if this was intended or not  but it still an issue why products only shown when using this specific google.json

**Comment by mustafaaycll** [comment]
It is intended

**Comment by mynameismhmd** [comment]
plz fix it it I wanna use your app for my project

**Comment by mustafaaycll** [comment]
Of course it will not work with a different json file. Create your own database in firebase. You can understand the DB structure by inspecting the /mobile/lib/Services/database.dart. Fill it with data and replace it with your own json file. What kind of a project is it anyway?

**Comment by mustafaaycll** [comment]
Also google-services.json you have is no longer a valid configuration file for my DB. It should not have been put here in the first place.

**Comment by mynameismhmd** [comment]
I did that already still not shown my project is a shoe app hope you change your code to make products shown to other people

**Comment by mynameismhmd** [comment]
I didn't find any solutions other than asking you to make it accept showing products to us

**Comment by UsetUset2244** [comment]
yes please fix it its also an issue for me
